# Generated by Django 4.1.3 on 2023-02-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
