"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 3.2.5.
For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import os.path
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv
from pytimeparse import parse
from decouple import config


def get_list(text):
    return [item.strip() for item in text.split(",")]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_PROJECT = Path(__file__).resolve().parent.parent.parent

load_dotenv(os.path.join(ROOT_PROJECT, 'common.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

_DEFAULT_CLIENT_HOSTS = "*"
ALLOWED_CLIENT_HOSTS = config("DJANGO_ALLOWED_HOSTS")


# REDIS = 'localhost' if DEBUG else 'redis'  # redis is docker service name

# ALLOWED_HOSTS = get_list(ALLOWED_CLIENT_HOSTS)
ALLOWED_HOSTS = ['*']

PROJECT_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'graphene_django',
    'corsheaders',
    'graphql_jwt.refresh_token.apps.RefreshTokenConfig',
    "django_filters",
    'import_export',
    'channels',
    'common',
    'chat',
    'appointment',
    'auth_extend',
    "notification"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]

TRUSTED_CORS_ORIGINS = config("TRUSTED_CORS_ORIGINS").split(',')

CSRF_TRUSTED_ORIGINS = TRUSTED_CORS_ORIGINS
CORS_ORIGIN_WHITELIST = TRUSTED_CORS_ORIGINS
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

DATABASES = {
    'default': dj_database_url.parse(f'{config("DATABASE_URL")}')
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'EN-US'

TIME_ZONE = 'UTC'

TIME_ZONE = "UTC"
LANGUAGE_CODE = "EN"

LANGUAGES = [
    ("EN", "English"),
    ("PT", "Portuguese"),
]
LOCALE_PATHS = [os.path.join(PROJECT_ROOT, "locale")]
USE_I18N = True
USE_L10N = True
USE_TZ = True
AUTH_USER_MODEL = 'api.User'

MEDIA_ROOT = os.path.join(PROJECT_ROOT, "media")
# MEDIA_URL = os.environ.get("MEDIA_URL", "/media/")
MEDIA_URL = config("MEDIA_URL", "/media/")

STATIC_ROOT = os.path.join(PROJECT_ROOT, "static")
# STATIC_URL = os.environ.get("STATIC_URL", "/static/")
STATIC_URL = config("STATIC_URL", "/static/")
STATICFILES_DIRS = [
    ("images", os.path.join(PROJECT_ROOT, "static", "images"))
]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL = config("ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL")

ENABLE_SSL = config("ENABLE_SSL")

if ENABLE_SSL:
    SECURE_SSL_REDIRECT = not DEBUG


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GRAPHENE = {
    "SCHEMA": "api.graphql.schema.schema_api",
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}

AUTHENTICATION_BACKENDS = [
    "graphql_jwt.backends.JSONWebTokenBackend",
    'django.contrib.auth.backends.ModelBackend',
]

JWT_ALLOW_ANY_CLASSES = [
    'api.graphql.mutations.user_mutation.CreateUserMutation',
]
GRAPHQL_JWT = {
    "JWT_ALLOW_ARGUMENT": True,
    "JWT_VERIFY_EXPIRATION": True,
    "JWT_LONG_RUNNING_REFRESH_TOKEN": True,
    "JWT_EXPIRATION_DELTA": timedelta(days=7),
    "JWT_REFRESH_EXPIRATION_DELTA": timedelta(days=7),
}


JWT_TTL_REQUEST_EMAIL_CHANGE = timedelta(
    seconds=parse(config("JWT_TTL_REQUEST_EMAIL_CHANGE", "1 hour")),
)

# CELERY SETTINGS
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_URL = (config("CELERY_BROKER_URL") or "")
CELERY_TASK_ALWAYS_EAGER = not CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        "CONFIG": {
            "hosts": [f'{config("REDIS_URL")}'],
        },
    },
}

STREAM_SOCKET_GROUP_NAME = 'system_detail'
APPEND_SLASH = False

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_PORT = config('EMAIL_PORT')