# Generated by Django 4.1.3 on 2023-02-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
